-- AUTO-GENERATED from app/public/skills.json by scripts/generate-skills-seed.mjs. Do not edit by hand.
-- Idempotent: adds new catalog skills and removes catalog skills no longer in the list
-- (unless a student still references one, which the FK will block — resolve those first).
begin;

insert into valid_skills (name) values
  ('.NET'),
  ('3D Modeling'),
  ('3D modelling'),
  ('5S methodology'),
  ('Abrasive blasting processes'),
  ('Abrasive machining processes'),
  ('Academic English'),
  ('Accounting'),
  ('Accounting entries'),
  ('Accounting techniques'),
  ('Acoustics'),
  ('Acting techniques'),
  ('Action research'),
  ('Adaptability'),
  ('Adhesives'),
  ('Adobe Acrobat'),
  ('Adobe After Effects'),
  ('Adobe Creative Cloud software'),
  ('Adobe Illustrator'),
  ('Adobe InDesign'),
  ('Adobe Photoshop'),
  ('Adolescence medicine'),
  ('Adolescent psychological development'),
  ('Adolescent socialisation behaviour'),
  ('Adult education'),
  ('Advertising techniques'),
  ('Aerodynamics'),
  ('Aeronomy'),
  ('Aerospace engineering'),
  ('Aesthetics'),
  ('African studies'),
  ('Agricultural chemicals'),
  ('Agritourism'),
  ('Agronomical production principles'),
  ('Agronomy'),
  ('Air force operations'),
  ('Aircraft mechanics'),
  ('AJAX'),
  ('Albanian'),
  ('Alcoholic beverage products'),
  ('Algebra'),
  ('Algorithms'),
  ('Allergies'),
  ('Alloys of precious metals'),
  ('Alternative energy'),
  ('Alteryx software'),
  ('Alumina ceramic'),
  ('Amazon DynamoDB'),
  ('Amazon Elastic Compute Cloud EC2'),
  ('Amazon Redshift'),
  ('Amazon Simple Storage Service S3'),
  ('Amazon Web Services AWS CloudFormation'),
  ('Amazon Web Services AWS software'),
  ('Analytical chemistry'),
  ('Ancient Greek'),
  ('Android Development'),
  ('Angular'),
  ('Animal biology'),
  ('Animal nutrition'),
  ('Animal species'),
  ('Animal welfare'),
  ('Animal welfare legislation'),
  ('Anodising process'),
  ('Ansible software'),
  ('Apache Cassandra'),
  ('Apache Hadoop'),
  ('Apache Hive'),
  ('Apache Kafka'),
  ('Apache Maven'),
  ('Apache Spark'),
  ('Apache Subversion SVN'),
  ('Apache Tomcat'),
  ('Apple iOS'),
  ('Apple macOS'),
  ('Aquaculture reproduction'),
  ('Aquatic ecology'),
  ('Aquatic species'),
  ('Arabic'),
  ('Armenian'),
  ('Artificial neural networks'),
  ('Asbestos removal regulations'),
  ('Asphalt mixes'),
  ('Assessment of risks and threats'),
  ('Assessment processes'),
  ('Asset management'),
  ('Assistive instruments'),
  ('Astronomy'),
  ('Atlassian Bamboo'),
  ('Atlassian Bitbucket'),
  ('Atlassian Confluence'),
  ('Atlassian JIRA'),
  ('Auction characteristics'),
  ('Audio editing software'),
  ('Audio technology'),
  ('Audit techniques'),
  ('Augmented reality'),
  ('Authoring software'),
  ('AutoCAD'),
  ('Autodesk AutoCAD'),
  ('Autodesk AutoCAD Civil 3D'),
  ('Autodesk Inventor'),
  ('Autodesk Revit'),
  ('Automatic control system'),
  ('Automatic meter reading'),
  ('Automation technology'),
  ('Aviation English'),
  ('AWS'),
  ('Azerbaijani'),
  ('Azure'),
  ('Banking activities'),
  ('Barbering techniques'),
  ('Bash'),
  ('Basic chemicals'),
  ('Basque'),
  ('Battery chemistry'),
  ('Battery components'),
  ('Battery fluids'),
  ('Behavioural disorders'),
  ('Behavioural science'),
  ('Belarusian'),
  ('Bengali'),
  ('Bentley MicroStation'),
  ('Berber'),
  ('Bicycle mechanics'),
  ('Bicycle sharing systems'),
  ('Bihari'),
  ('Bioeconomy'),
  ('Biological haematology'),
  ('Biology'),
  ('Biomechanics'),
  ('Biomedical engineering'),
  ('Biomedical science'),
  ('Biomedical techniques'),
  ('Biometrics'),
  ('Biophysics'),
  ('Biosecurity'),
  ('Biostatistics'),
  ('Biotechnology'),
  ('Biotechnology in aquaculture'),
  ('Blender'),
  ('Blockchain application areas'),
  ('Blockchain applications'),
  ('Blockchain concept application'),
  ('Blockchain-based services regulation'),
  ('Blood transfusion'),
  ('Blow moulding'),
  ('Blueprints'),
  ('Body language'),
  ('Book reviews'),
  ('Bookkeeping regulations'),
  ('Bootstrap'),
  ('Border Gateway Protocol BGP'),
  ('Bosnian'),
  ('Brand marketing techniques'),
  ('Breathing techniques'),
  ('Budgeting'),
  ('Buffing motions'),
  ('Building automation'),
  ('Building codes'),
  ('Building construction principles'),
  ('Building materials industry'),
  ('Bulgarian'),
  ('Business analysis'),
  ('Business communication'),
  ('Business Development'),
  ('Business incubation'),
  ('Business intelligence'),
  ('Business law'),
  ('Business loans'),
  ('Business management principles'),
  ('Business processes'),
  ('Business strategy concepts'),
  ('Business valuation techniques'),
  ('By-products'),
  ('C#'),
  ('C++'),
  ('CAD software'),
  ('Cadastral taxation'),
  ('CADD software'),
  ('CAE software'),
  ('Call quality assurance management'),
  ('Call routing'),
  ('Call-centre technologies'),
  ('Cameras'),
  ('Cancellation policies of service providers'),
  ('Candle making techniques'),
  ('Canva'),
  ('Capacity building'),
  ('Carpentry'),
  ('Cascading style sheets CSS'),
  ('Catalan'),
  ('Centrifugal force'),
  ('Ceramics glazes'),
  ('Channel marketing'),
  ('Characteristics of diamonds'),
  ('Characteristics of faces'),
  ('Characteristics of plants'),
  ('Characteristics of precious metals'),
  ('Check methods'),
  ('Chef'),
  ('Chemical preservation'),
  ('Chemistry'),
  ('Chemistry of wood'),
  ('Child protection'),
  ('Childbirth'),
  ('Chinese'),
  ('CI/CD'),
  ('Circular economy'),
  ('Circus aesthetics'),
  ('Cisco Webex'),
  ('Civil engineering'),
  ('Civil law'),
  ('Civil process order'),
  ('Classical antiquity'),
  ('Classical languages'),
  ('Cleaning products'),
  ('Cleaning techniques'),
  ('Climate change impact'),
  ('Climatology'),
  ('Clinical biochemistry'),
  ('Clinical cytology'),
  ('Clinical imaging techniques'),
  ('Clinical immunology'),
  ('Clinical microbiology'),
  ('Coaching techniques'),
  ('Coating substances'),
  ('Coffee characteristics'),
  ('Cognitive psychology'),
  ('Coining'),
  ('Cold forging'),
  ('Combination of flavours'),
  ('Commercial photography'),
  ('Common children''s diseases'),
  ('Communicable diseases'),
  ('Communication'),
  ('Communication disorders'),
  ('Communication principles'),
  ('Communication related to hearing impairment'),
  ('Communication sciences'),
  ('Communication studies'),
  ('Community education'),
  ('Community-led local development'),
  ('Compass navigation'),
  ('Competition law'),
  ('Composite materials'),
  ('Composition of diets'),
  ('Computational fluid dynamics'),
  ('Computer engineering'),
  ('Computer graphics'),
  ('Computer programming'),
  ('Computer science'),
  ('Computer simulation'),
  ('Computer technology'),
  ('Computer Vision'),
  ('Concurrent estate'),
  ('Conflict management'),
  ('Conflict Resolution'),
  ('Constitutional law'),
  ('Construction industry'),
  ('Construction legal systems'),
  ('Construction methods'),
  ('Consultation'),
  ('Consulting'),
  ('Consumer goods industry'),
  ('Consumer law'),
  ('Consumer protection'),
  ('Contamination exposure regulations'),
  ('Content development processes'),
  ('Content marketing strategy'),
  ('Content Writing'),
  ('Continuous improvement philosophies'),
  ('Contract law'),
  ('Control engineering'),
  ('Control systems'),
  ('Conveyancing'),
  ('Copyright legislation'),
  ('Copywriting'),
  ('Corporate law'),
  ('Correctional procedures'),
  ('Corrosion types'),
  ('Cosmetic dental procedures'),
  ('Cosmetic manicure'),
  ('Cosmetic pedicure'),
  ('Cosmetic skin treatment'),
  ('Counselling methods'),
  ('Court interpreting'),
  ('Court procedures'),
  ('Credit card payments'),
  ('Credit control processes'),
  ('Crime victims'' needs'),
  ('Crime victims'' rights'),
  ('Criminal law'),
  ('Criminology'),
  ('Crimping'),
  ('Crisis intervention'),
  ('Critical Thinking'),
  ('Croatian'),
  ('Cross-matching techniques for blood transfusions'),
  ('Crowdfunding'),
  ('Cultured pearls'),
  ('Curriculum objectives'),
  ('Curriculum standards'),
  ('Customer relationship management'),
  ('Customer segmentation'),
  ('Cutting technologies'),
  ('Czech'),
  ('Danish'),
  ('Dart'),
  ('Dassault Systemes SolidWorks'),
  ('Data Analysis'),
  ('Data analytics'),
  ('Data engineering'),
  ('Data ethics'),
  ('Data mining methods'),
  ('Data science'),
  ('Data visualisation software'),
  ('Data Visualization'),
  ('Database'),
  ('Debt classification'),
  ('Debt collection techniques'),
  ('Debt systems'),
  ('Deburring processes'),
  ('Deep learning'),
  ('Demography'),
  ('Dental anatomy'),
  ('Dentistry science'),
  ('Dependency on drugs'),
  ('Design drawings'),
  ('Design principles'),
  ('Design thinking'),
  ('Desktop publishing'),
  ('Deterioration of fish products'),
  ('Development delays'),
  ('Developmental psychology'),
  ('Diagnostic radiology'),
  ('Dies'),
  ('Dietary regimes'),
  ('Digital compositing'),
  ('Digital image processing'),
  ('Digital Marketing'),
  ('Digital media'),
  ('Digital systems'),
  ('Digitization'),
  ('Dip tank parts'),
  ('Dip-coating process'),
  ('Diplomatic principles'),
  ('Dipping tank types'),
  ('Disability types'),
  ('Diving equipment'),
  ('Diving operation requirements'),
  ('Django'),
  ('Docker'),
  ('Document sharing procedures'),
  ('Dog behaviour'),
  ('Domestic heating systems'),
  ('Dressmaking'),
  ('Driving examinations'),
  ('Drupal'),
  ('Dust usage for forging'),
  ('Dutch'),
  ('Earth science'),
  ('eClinicalWorks EHR software'),
  ('Eclipse IDE'),
  ('Eclipse Jersey'),
  ('Ecological principles'),
  ('Ecology'),
  ('Economics'),
  ('Ecosystems'),
  ('Editorial standards'),
  ('Education administration'),
  ('Education law'),
  ('Elasticsearch'),
  ('Election law'),
  ('Electric clocks'),
  ('Electric current'),
  ('Electric generators'),
  ('Electrical discharge'),
  ('Electrical engineering'),
  ('Electrical equipment regulations'),
  ('Electrical machines'),
  ('Electrical power safety regulations'),
  ('Electrical testing methods'),
  ('Electrical wiring diagrams'),
  ('Electrical wiring plans'),
  ('Electricity'),
  ('Electricity consumption'),
  ('Electricity market'),
  ('Electricity principles'),
  ('Electrolytic passivation process'),
  ('Electromagnetic spectrum'),
  ('Electromechanics'),
  ('Electronic communication'),
  ('Electronic equipment standards'),
  ('Electronic test procedures'),
  ('Electronics'),
  ('Electroplating'),
  ('Electroplating metal materials'),
  ('Electroplating processes'),
  ('Email Marketing'),
  ('Emergency cases'),
  ('Emergent technologies'),
  ('Emission standards'),
  ('Empirical analysis'),
  ('Employment law'),
  ('Energy'),
  ('Energy conservation'),
  ('Energy market'),
  ('Energy performance of buildings'),
  ('Energy storage systems'),
  ('Energy therapy'),
  ('Engine components'),
  ('Engineering principles'),
  ('English'),
  ('Engraving technologies'),
  ('Entrepreneurship'),
  ('Environmental engineering'),
  ('Environmental legislation'),
  ('Environmental management standards'),
  ('Environmental policy'),
  ('Enzymatic processing'),
  ('Epic Systems'),
  ('Epidemiology'),
  ('Ergonomics'),
  ('ESRI ArcGIS software'),
  ('Estonian'),
  ('Ethics'),
  ('Etiopathy'),
  ('Evolution of economic forecasts'),
  ('Excel (Advanced)'),
  ('Export control principles'),
  ('Express.js'),
  ('Extensible markup language XML'),
  ('Eye protection regulations'),
  ('Fabric types'),
  ('Facebook'),
  ('Family law'),
  ('Fasciatherapy'),
  ('Female reproductive system pathology'),
  ('Fertilisation principles'),
  ('Fibre optics'),
  ('Fibreglass laminating'),
  ('Figma'),
  ('Film studies'),
  ('Financial Analysis'),
  ('Financial capability'),
  ('Financial engineering'),
  ('Financial forecasting'),
  ('Financial jurisdiction'),
  ('Financial management'),
  ('Financial markets'),
  ('Financial Modeling'),
  ('Financial products'),
  ('Financial statements'),
  ('Fine arts'),
  ('Finnish'),
  ('Fire prevention procedures'),
  ('Fire protection engineering'),
  ('Fire safety regulations'),
  ('Fire-fighting systems'),
  ('Firebase'),
  ('Firmware'),
  ('First aid'),
  ('Fish identification and classification'),
  ('Fish varieties'),
  ('Fish welfare regulations'),
  ('Fisheries management'),
  ('Fishing industry'),
  ('Flammable fluids'),
  ('Flask'),
  ('Flood remediation equipment'),
  ('Floriculture'),
  ('Fluid mechanics'),
  ('Flutter'),
  ('Food colorants'),
  ('Footwear industry'),
  ('Foreign affairs'),
  ('Foreign affairs policy development'),
  ('Foreign languages for international careers'),
  ('Forensic anthropology'),
  ('Forensic intelligence'),
  ('Forensic linguistics'),
  ('Forest conservation'),
  ('Forest ecology'),
  ('Forging processes'),
  ('Forming of public opinion'),
  ('Fossil fuels'),
  ('Fraud detection'),
  ('Freight transport methods'),
  ('French'),
  ('Fuel cell types'),
  ('Fuel distribution systems'),
  ('Fuel gas'),
  ('Functionalities of machinery'),
  ('Fundamental veterinary sciences'),
  ('Funding methods'),
  ('Furniture wood types'),
  ('Galician'),
  ('Game theory'),
  ('Gas chromatography'),
  ('Gemstones'),
  ('Gender studies'),
  ('General medicine'),
  ('Geochemistry'),
  ('Geodesy'),
  ('Geographic areas'),
  ('Geographical routes'),
  ('Geography'),
  ('Geological time scale'),
  ('Geology'),
  ('Geomatics'),
  ('Geometry'),
  ('Geophysics'),
  ('Georgian'),
  ('Geriatrics'),
  ('German'),
  ('GIS/ArcGIS'),
  ('Git'),
  ('GitHub'),
  ('GitLab'),
  ('Glass coatings'),
  ('Glass tempering'),
  ('Glassworking'),
  ('Go'),
  ('Good laboratory practice'),
  ('Google Analytics'),
  ('Google Android'),
  ('Google Angular'),
  ('Google Cloud'),
  ('Google Docs'),
  ('Google Sheets'),
  ('Google Workspace software'),
  ('Government policy'),
  ('Government policy implementation'),
  ('Government representation'),
  ('Government social security programmes'),
  ('Grammar'),
  ('Graphic design'),
  ('GraphQL'),
  ('Greek'),
  ('Green logistics'),
  ('Green space strategies'),
  ('Gujarati'),
  ('Hair colouring'),
  ('Hair products'),
  ('Hair removal techniques'),
  ('Hairdressing'),
  ('Handling of dangerous goods'),
  ('Hardware components'),
  ('Hardware industry'),
  ('Hardware testing methods'),
  ('Hazardous waste storage'),
  ('Hazardous waste treatment'),
  ('Hazardous waste types'),
  ('Health and safety hazards underground'),
  ('Health and safety regulations'),
  ('Health care legislation'),
  ('Health care occupation-specific ethics'),
  ('Health care system'),
  ('Health education'),
  ('Health informatics'),
  ('Health, safety and hygiene legislation'),
  ('Hearing aids'),
  ('Hearing disability'),
  ('Hebrew'),
  ('Henry Schein Dentrix'),
  ('Herbicides'),
  ('Hibernate ORM'),
  ('Hindi'),
  ('Histology'),
  ('Historic architecture'),
  ('Historical methods'),
  ('History'),
  ('History of literature'),
  ('History of musical instruments'),
  ('History of philosophy'),
  ('History of theology'),
  ('Homeopathy'),
  ('Hoshin kanri strategic planning'),
  ('Hot forging'),
  ('HubSpot software'),
  ('Human anatomy'),
  ('Human ear'),
  ('Human physiology'),
  ('Human resource management'),
  ('Human resources department processes'),
  ('Humanitarian aid actors'),
  ('Hungarian'),
  ('Hybrid control systems'),
  ('Hydraulic fluid'),
  ('Hydraulic press parts'),
  ('Hydraulics'),
  ('Hydroelectricity'),
  ('Hypertext markup language HTML'),
  ('IBM DB2'),
  ('IBM SPSS Statistics'),
  ('IBM Terraform'),
  ('IBM WebSphere MQ'),
  ('Icelandic'),
  ('ICT hardware specifications'),
  ('ICT networking hardware'),
  ('Illegal substances'),
  ('Image formation'),
  ('Image recognition'),
  ('Immigration law'),
  ('Immunology'),
  ('Industrial design'),
  ('Industrial engineering'),
  ('Industrial heating systems'),
  ('Industrial paint'),
  ('Industrial research and development'),
  ('Industrial software'),
  ('Infection control'),
  ('Infections in food'),
  ('Informatica software'),
  ('Innovation in nursing'),
  ('Inorganic chemistry'),
  ('Insolvency law'),
  ('Instrument performance elements'),
  ('Instrumentation engineering'),
  ('Instrumentation equipment'),
  ('Insurance law'),
  ('Insurance market'),
  ('Integrated circuits'),
  ('Integrated food-energy systems'),
  ('Intellectual property law'),
  ('Interactive media'),
  ('Internal auditing'),
  ('International business'),
  ('International development'),
  ('International financial reporting standards'),
  ('International law'),
  ('International regulations for cargo handling'),
  ('International trade'),
  ('Interpreting modes'),
  ('Interview techniques'),
  ('Intuit QuickBooks'),
  ('Inventory management rules'),
  ('Investigation research methods'),
  ('iOS Development'),
  ('Irish'),
  ('Italian'),
  ('Japanese'),
  ('Java'),
  ('Javanese'),
  ('JavaScript'),
  ('JavaScript Object Notation JSON'),
  ('Jenkins'),
  ('Jenkins CI'),
  ('Job market offers'),
  ('Joint ventures'),
  ('Journalism'),
  ('jQuery'),
  ('JUnit'),
  ('Jupyter Notebooks'),
  ('Kazakh'),
  ('Kiln types'),
  ('Kindergarten school procedures'),
  ('Kinetics'),
  ('Knowledge base'),
  ('Korean'),
  ('Kotlin'),
  ('Kronos Workforce Timekeeper'),
  ('Kubernetes'),
  ('Kurdish'),
  ('Laboratory methods in biomedical sciences'),
  ('Laboratory techniques'),
  ('Laboratory-based sciences'),
  ('Labour legislation'),
  ('Labour market'),
  ('LabVIEW'),
  ('Lacquer paint applications'),
  ('Landscape analysis'),
  ('Language teaching methods'),
  ('Laravel'),
  ('Laser engraving methods'),
  ('Laser marking processes'),
  ('Laser types'),
  ('Lasers'),
  ('Lathe machine parts'),
  ('Latin'),
  ('Latvian'),
  ('Launching of satellites into orbit'),
  ('Law enforcement'),
  ('Law of non-marital cohabitation'),
  ('Law of obligation'),
  ('Leadership'),
  ('Leadership principles'),
  ('Lean manufacturing'),
  ('Learning difficulties'),
  ('Learning management systems'),
  ('Learning needs analysis'),
  ('Leasing characteristics'),
  ('Leasing process'),
  ('Leather colour chemistry'),
  ('Legal case management'),
  ('Legal requirements of ICT products'),
  ('Legal research'),
  ('Legal terminology'),
  ('Legal use-of-force'),
  ('Legislation in agriculture'),
  ('Legislation procedure'),
  ('Licences regulation'),
  ('Life sciences'),
  ('Lift safety legislation'),
  ('Lift safety mechanisms'),
  ('Lighting techniques'),
  ('Limburgish'),
  ('Linguistics'),
  ('Linux'),
  ('Lip reading'),
  ('Liquidity management'),
  ('Literary criticism'),
  ('Literary techniques'),
  ('Literature'),
  ('Lithuanian'),
  ('Local geography'),
  ('Logic'),
  ('Logistics'),
  ('Luxembourgish'),
  ('Macedonian'),
  ('Machine Learning'),
  ('Machinery load capacity'),
  ('Maintenance operations'),
  ('Make-up techniques'),
  ('Malay'),
  ('Maltese'),
  ('Manage healthcare staff'),
  ('Management department processes'),
  ('Manual draughting techniques'),
  ('Manufacturing processes'),
  ('Marathi'),
  ('Marine engineering'),
  ('Marine technology'),
  ('Market analysis'),
  ('Market entry planning'),
  ('Market entry strategies'),
  ('Market participants'),
  ('Market Research'),
  ('Marketing analytics'),
  ('Marketing management'),
  ('Marketing mix'),
  ('Marketing principles'),
  ('Marketo Marketing Automation'),
  ('Massage theory'),
  ('Massage types'),
  ('Material mechanics'),
  ('Materials engineering'),
  ('Mathematical modelling'),
  ('Mathematics'),
  ('MATLAB'),
  ('Mechanical clocks'),
  ('Mechanical composition of trams'),
  ('Mechanical forging press parts'),
  ('Mechanical systems'),
  ('Mechanical tools'),
  ('Mechanics'),
  ('Mechanics of motor vehicles'),
  ('Mechanics of trains'),
  ('Mechatronics'),
  ('Media law'),
  ('Media planning'),
  ('Media studies'),
  ('Medical device regulations'),
  ('Medical device test procedures'),
  ('Medical devices'),
  ('Medical devices materials'),
  ('Medical genetics'),
  ('Medical imaging technology'),
  ('Medical informatics'),
  ('Medical laboratory technology'),
  ('Medical statistics'),
  ('Medical studies'),
  ('Medical terminology'),
  ('Medicines'),
  ('MEDITECH software'),
  ('Mentoring'),
  ('Mergers and acquisitions'),
  ('Metal bending techniques'),
  ('Metal coating technologies'),
  ('Metal drawing processes'),
  ('Metal eroding technology'),
  ('Metal forming technologies'),
  ('Metal joining technologies'),
  ('Metal smoothing technologies'),
  ('Metal thermal conductivity'),
  ('Metallurgy'),
  ('Metalworking tools'),
  ('Meteorology'),
  ('Metrology'),
  ('Microassembly'),
  ('Microelectronics'),
  ('Micromechanics'),
  ('Microprocessors'),
  ('Microscopic techniques'),
  ('Microsensors'),
  ('Microsoft .NET Framework'),
  ('Microsoft Access'),
  ('Microsoft Active Directory'),
  ('Microsoft Active Server Pages ASP'),
  ('Microsoft ASP.NET'),
  ('Microsoft Azure software'),
  ('Microsoft Dynamics'),
  ('Microsoft Excel'),
  ('Microsoft Office software'),
  ('Microsoft Outlook'),
  ('Microsoft Power BI'),
  ('Microsoft PowerPoint'),
  ('Microsoft PowerShell'),
  ('Microsoft Project'),
  ('Microsoft SharePoint'),
  ('Microsoft SQL Server'),
  ('Microsoft SQL Server Integration Services SSIS'),
  ('Microsoft SQL Server Reporting Services SSRS'),
  ('Microsoft Team Foundation Server'),
  ('Microsoft Teams'),
  ('Microsoft Visio'),
  ('Microsoft Visual Basic'),
  ('Microsoft Visual Basic for Applications VBA'),
  ('Microsoft Visual Studio'),
  ('Microsoft Windows'),
  ('Microsoft Windows Server'),
  ('Microsoft Word'),
  ('Migration'),
  ('Military code'),
  ('Military combat techniques'),
  ('Military drill'),
  ('Military logistics'),
  ('Military weaponry'),
  ('Mobility disability'),
  ('Model based system engineering'),
  ('Modern languages'),
  ('Modern portfolio theory'),
  ('Molecular biology'),
  ('MongoDB'),
  ('Monte Carlo simulation'),
  ('Montenegrin'),
  ('Morality'),
  ('Mortgage loans'),
  ('Motion graphics'),
  ('Motor vehicle parts drawings'),
  ('Movement techniques'),
  ('Multidisciplinary research'),
  ('Multimedia systems'),
  ('Multimodal transport logistics'),
  ('Musculoskeletal anatomy'),
  ('Music and video industry'),
  ('Musical genres'),
  ('Musical notation'),
  ('MySQL'),
  ('Nanoelectronics'),
  ('Nanotechnology'),
  ('National generally accepted accounting principles'),
  ('National regulations on handling cargo'),
  ('Natural Language Processing'),
  ('Neurology'),
  ('Neurophysiology'),
  ('New vehicles on the market'),
  ('Newborn care'),
  ('Next.js'),
  ('Node.js'),
  ('Non-destructive testing'),
  ('Norwegian'),
  ('NoSQL'),
  ('Nuclear energy'),
  ('Nuclear medicine'),
  ('Nuclear reprocessing'),
  ('Numerical sequences'),
  ('NumPy'),
  ('Nursing principles'),
  ('Nursing science'),
  ('Occitan'),
  ('Occupational physiology'),
  ('Occupational therapy theories'),
  ('Oceanography'),
  ('Office software'),
  ('Older adults'' needs'),
  ('Online ads campaign techniques'),
  ('Operational research'),
  ('Operational tactics for emergency responses'),
  ('Opinion poll'),
  ('Optical character recognition software'),
  ('Optical components'),
  ('Optical engineering'),
  ('Optical equipment standards'),
  ('Optical glass characteristics'),
  ('Optical instruments'),
  ('Optics'),
  ('Optoelectronic devices'),
  ('Optoelectronics'),
  ('Optomechanical engineering'),
  ('Oracle Cloud software'),
  ('Oracle Database'),
  ('Oracle Java'),
  ('Oracle Java 2 Platform Enterprise Edition J2EE'),
  ('Oracle JavaServer Pages JSP'),
  ('Oracle PeopleSoft'),
  ('Oracle PL/SQL'),
  ('Oracle SQL Developer'),
  ('Oral surgery'),
  ('Organic chemistry'),
  ('Organisational structure'),
  ('Orthopaedic treatment alternatives'),
  ('Orthopaedics'),
  ('Packaging engineering'),
  ('Packaging functions'),
  ('Packaging processes'),
  ('Paediatrics'),
  ('Paleontology'),
  ('Pandas'),
  ('Paper chemistry'),
  ('Paper production processes'),
  ('Participant observation'),
  ('Participatory decision-making'),
  ('Patents'),
  ('Pathogenic microorganisms'),
  ('Pathology'),
  ('Pedagogy'),
  ('Peer group methods'),
  ('Percolation'),
  ('Periodisation'),
  ('Perl'),
  ('Persian'),
  ('Personal development'),
  ('Personal protective equipment'),
  ('Personality development theories'),
  ('Personnel management'),
  ('Pest control in plants'),
  ('Pet diseases'),
  ('Pharmaceutical chemistry'),
  ('Pharmaceutical drug development'),
  ('Pharmaceutical industry'),
  ('Pharmaceutical legislation'),
  ('Pharmaceutical manufacturing quality systems'),
  ('Pharmaceutical technology'),
  ('Pharmacokinetics'),
  ('Pharmacology'),
  ('Pharmacovigilance legislation'),
  ('Pharmacy law'),
  ('Philanthropy'),
  ('Philosophical schools of thought'),
  ('Philosophy'),
  ('Phonetics'),
  ('Photogrammetry'),
  ('Photographic lenses'),
  ('Photographic processing techniques'),
  ('Photography'),
  ('Photonics'),
  ('PHP'),
  ('Physics'),
  ('Plastic resins'),
  ('Plastic welding'),
  ('Plumbing tools'),
  ('Pneumatics'),
  ('Polish'),
  ('Political campaigning'),
  ('Political ideologies'),
  ('Political parties'),
  ('Political science'),
  ('Politics'),
  ('Polling techniques'),
  ('Pollution prevention'),
  ('Polymer chemistry'),
  ('Portfolio management in textile manufacturing'),
  ('Portuguese'),
  ('Post-processing of photographs'),
  ('PostgreSQL'),
  ('Power BI'),
  ('Power electronics'),
  ('Power engineering'),
  ('Practical lexicography'),
  ('Precious metals'),
  ('Precision engineering'),
  ('Precision measuring instruments'),
  ('Precision mechanics'),
  ('Prepress processes'),
  ('Press law'),
  ('Preventive medicine'),
  ('Pricing strategies'),
  ('Primary care'),
  ('Primary school procedures'),
  ('Principles of combustion engines'),
  ('Principles of mechanical engineering'),
  ('Printed circuit boards'),
  ('Printed circuit boards testing methods'),
  ('Printed goods processes'),
  ('Printing media'),
  ('Printing techniques'),
  ('Probability theory'),
  ('Problem Solving'),
  ('Procore software'),
  ('Procurement legislation'),
  ('Product data management'),
  ('Product packaging requirements'),
  ('Product usage risks analysis'),
  ('Production processes'),
  ('Programmable logic controller'),
  ('Project configuration management'),
  ('Project Management'),
  ('Project management methodology'),
  ('Project management principles'),
  ('Pronunciation techniques'),
  ('Property law'),
  ('Protection from natural elements'),
  ('Prototyping'),
  ('Psychiatric disorders'),
  ('Psychiatry'),
  ('Psychological concepts'),
  ('Psychological counselling methods'),
  ('Psychological diagnostics'),
  ('Psychological theories'),
  ('Psychological treatment measures'),
  ('Psychology'),
  ('Psychotherapy principles'),
  ('Public auction procedures'),
  ('Public finance'),
  ('Public health'),
  ('Public housing legislation'),
  ('Public law'),
  ('Public offering'),
  ('Public relations'),
  ('Public Speaking'),
  ('Publishing industry'),
  ('Punjabi'),
  ('Puppet'),
  ('Pyrotechnic articles legislation'),
  ('Python'),
  ('PyTorch'),
  ('Quality and cycle time optimisation'),
  ('Quality assurance methodologies'),
  ('Quality assurance procedures'),
  ('Quality of fish products'),
  ('Quality standards'),
  ('Quantitative analysis'),
  ('Radars'),
  ('Radiation physics in healthcare'),
  ('Radiation protection'),
  ('Railway law'),
  ('React'),
  ('React Native'),
  ('Real estate market'),
  ('Recreation activities'),
  ('Red Hat Enterprise Linux'),
  ('Red Hat OpenShift'),
  ('Redis'),
  ('Reflexology'),
  ('Refractive power'),
  ('Refrigerants'),
  ('Rehabilitation'),
  ('Relationship marketing'),
  ('Relaxation techniques'),
  ('Religious studies'),
  ('Remote sensing techniques'),
  ('Renewable energy'),
  ('Repossession'),
  ('Reprography'),
  ('Reputation management'),
  ('Research design'),
  ('Resource-efficient technologies'),
  ('Restorative justice'),
  ('Resuscitation'),
  ('Reverse engineering'),
  ('Revit'),
  ('Rhetoric'),
  ('Risk assessment for window cleaning'),
  ('Risk identification'),
  ('Risk management'),
  ('Risk transfer'),
  ('Rivet types'),
  ('Riveting machine types'),
  ('Road traffic laws'),
  ('Robotic components'),
  ('Robotics'),
  ('Romani'),
  ('Romanian'),
  ('Room aesthetics'),
  ('Root cause analysis'),
  ('Rope lashing'),
  ('Ruby'),
  ('Ruby on Rails'),
  ('Russian'),
  ('Rust'),
  ('Safety engineering'),
  ('Sales'),
  ('Sales department processes'),
  ('Salesforce software'),
  ('Salon management'),
  ('Sanding techniques'),
  ('Sanskrit'),
  ('SAP Concur'),
  ('SAP ERP'),
  ('SAP software'),
  ('Sardinian'),
  ('SAS'),
  ('Scaffolding components'),
  ('Scala'),
  ('School psychology'),
  ('Scientific computing'),
  ('Scientific literature'),
  ('Scientific modelling'),
  ('Scientific research methodology'),
  ('Scikit-learn'),
  ('Screen reader'),
  ('Screw types'),
  ('Secondary school procedures'),
  ('Securities'),
  ('Security engineering'),
  ('Security of assets legislation'),
  ('Security panels'),
  ('Security threats'),
  ('Selenium'),
  ('Semantics'),
  ('Semiconductors'),
  ('Sensors'),
  ('SEO/SEM'),
  ('Serbian'),
  ('ServiceNow'),
  ('Sex education'),
  ('Sexology'),
  ('Shell script'),
  ('Shell/Bash'),
  ('Sign language'),
  ('Sketch'),
  ('SketchUp'),
  ('Skin types'),
  ('Slack'),
  ('Slovak'),
  ('Slovenian'),
  ('SMED'),
  ('Social justice'),
  ('Social media management'),
  ('Social Media Marketing'),
  ('Social media marketing techniques'),
  ('Social network analysis'),
  ('Social pedagogy'),
  ('Social sciences'),
  ('Social security law'),
  ('Social work theory'),
  ('Sociology'),
  ('Soil science'),
  ('Solar energy'),
  ('Solar products'),
  ('Soldering techniques'),
  ('SolidWorks'),
  ('Source colour chemicals'),
  ('Source criticism'),
  ('Spanish'),
  ('Special needs education'),
  ('Speech techniques'),
  ('Spelling'),
  ('Splunk Enterprise'),
  ('Sport and exercise medicine'),
  ('Sport games rules'),
  ('Sport history'),
  ('Sports competition information'),
  ('Sports nutrition'),
  ('Spring Boot'),
  ('Spring Framework'),
  ('SPSS'),
  ('SQL'),
  ('Stata'),
  ('State estimation'),
  ('Statistical analysis system software'),
  ('Statistical process control'),
  ('Statistics'),
  ('Stenography'),
  ('Sterilization techniques'),
  ('Stock market'),
  ('Strategic Planning'),
  ('Structured query language SQL'),
  ('Style sheet languages'),
  ('Subsidiary operations'),
  ('Supabase'),
  ('Supervision of persons'),
  ('Supply chain management'),
  ('Supply chain principles'),
  ('Surface engineering'),
  ('Surveillance methods'),
  ('Survey techniques'),
  ('Surveying'),
  ('Sustainable development goals'),
  ('Sustainable manufacturing'),
  ('Sustainable technologies'),
  ('Svelte'),
  ('Swedish'),
  ('Swift'),
  ('Swimming pool chemicals'),
  ('Synthetic resins'),
  ('System backup best practice'),
  ('Systems development life-cycle'),
  ('Tableau'),
  ('Tailwind CSS'),
  ('Tamil'),
  ('Task algorithmisation'),
  ('Tax legislation'),
  ('Teamwork'),
  ('Teamwork principles'),
  ('Technical drawings'),
  ('Technical terminology'),
  ('Telecommunication industry'),
  ('Telecommunications engineering'),
  ('Telemarketing'),
  ('Telugu'),
  ('Temperature scales'),
  ('TensorFlow'),
  ('Teradata Database'),
  ('Terminology'),
  ('Terraform'),
  ('Test procedures'),
  ('Textile industry'),
  ('Textile measurement'),
  ('Textile printing technology'),
  ('Textile technologies'),
  ('Textile trends'),
  ('The MathWorks MATLAB'),
  ('Theology'),
  ('Theoretical lexicography'),
  ('Theories of personality'),
  ('Therapeutic massage'),
  ('Thermodynamics'),
  ('Thermoplastic materials'),
  ('TikTok'),
  ('Time Management'),
  ('Torch temperature for metal processes'),
  ('Toxicology'),
  ('Toys and games categories'),
  ('Toys and games industry'),
  ('Toys and games safety recommendations'),
  ('Toys and games trends'),
  ('Track geometry'),
  ('Trade union regulations'),
  ('Trademarks'),
  ('Trading law'),
  ('Traffic engineering'),
  ('Traffic signs'),
  ('Training subject expertise'),
  ('Transact-SQL'),
  ('Transcription methods'),
  ('Transmission technology'),
  ('Transmission towers'),
  ('Transport topography'),
  ('Transportation engineering'),
  ('Travel bookings processes'),
  ('Trends in fashion'),
  ('Trendwatching'),
  ('Trimble SketchUp Pro'),
  ('Turkish'),
  ('Type of file'),
  ('TypeScript'),
  ('Typography'),
  ('UI/UX Design'),
  ('Ukrainian'),
  ('Understand spoken Luxembourgish'),
  ('UNIX'),
  ('UNIX Shell'),
  ('Upholstery tools'),
  ('Urban planning'),
  ('Urban planning law'),
  ('Urdu'),
  ('Value-added tax law'),
  ('Ventilation systems'),
  ('Victimology'),
  ('Video Editing'),
  ('Video-games functionalities'),
  ('Video-games trends'),
  ('Vietnamese'),
  ('Vinyl records'),
  ('Virology'),
  ('Virtual reality'),
  ('Visual disability'),
  ('Visual flight rules'),
  ('Vocal techniques'),
  ('Vue.js'),
  ('Walloon'),
  ('Waste management'),
  ('Waste transport legislation'),
  ('Water policies'),
  ('Water pressure'),
  ('Water reuse'),
  ('Web analytics'),
  ('Welding techniques'),
  ('Welsh'),
  ('Wet tumbling'),
  ('Wicker materials'),
  ('Wicker weaving techniques'),
  ('Wire harnesses'),
  ('Wireframing'),
  ('Wood cuts'),
  ('Wood moisture content'),
  ('Woodworking processes'),
  ('Woodworking tools'),
  ('WordPress'),
  ('Workday software'),
  ('Workplace sanitation'),
  ('World Wide Web Consortium standards'),
  ('Writing style guides'),
  ('Writing techniques'),
  ('Written Communication'),
  ('Yardi software'),
  ('Yeast fermentation principles'),
  ('Yiddish'),
  ('Zoning codes'),
  ('Zoo regulations'),
  ('Zoom')
on conflict (name) do nothing;

delete from valid_skills
  where name not in (
    '.NET',
    '3D Modeling',
    '3D modelling',
    '5S methodology',
    'Abrasive blasting processes',
    'Abrasive machining processes',
    'Academic English',
    'Accounting',
    'Accounting entries',
    'Accounting techniques',
    'Acoustics',
    'Acting techniques',
    'Action research',
    'Adaptability',
    'Adhesives',
    'Adobe Acrobat',
    'Adobe After Effects',
    'Adobe Creative Cloud software',
    'Adobe Illustrator',
    'Adobe InDesign',
    'Adobe Photoshop',
    'Adolescence medicine',
    'Adolescent psychological development',
    'Adolescent socialisation behaviour',
    'Adult education',
    'Advertising techniques',
    'Aerodynamics',
    'Aeronomy',
    'Aerospace engineering',
    'Aesthetics',
    'African studies',
    'Agricultural chemicals',
    'Agritourism',
    'Agronomical production principles',
    'Agronomy',
    'Air force operations',
    'Aircraft mechanics',
    'AJAX',
    'Albanian',
    'Alcoholic beverage products',
    'Algebra',
    'Algorithms',
    'Allergies',
    'Alloys of precious metals',
    'Alternative energy',
    'Alteryx software',
    'Alumina ceramic',
    'Amazon DynamoDB',
    'Amazon Elastic Compute Cloud EC2',
    'Amazon Redshift',
    'Amazon Simple Storage Service S3',
    'Amazon Web Services AWS CloudFormation',
    'Amazon Web Services AWS software',
    'Analytical chemistry',
    'Ancient Greek',
    'Android Development',
    'Angular',
    'Animal biology',
    'Animal nutrition',
    'Animal species',
    'Animal welfare',
    'Animal welfare legislation',
    'Anodising process',
    'Ansible software',
    'Apache Cassandra',
    'Apache Hadoop',
    'Apache Hive',
    'Apache Kafka',
    'Apache Maven',
    'Apache Spark',
    'Apache Subversion SVN',
    'Apache Tomcat',
    'Apple iOS',
    'Apple macOS',
    'Aquaculture reproduction',
    'Aquatic ecology',
    'Aquatic species',
    'Arabic',
    'Armenian',
    'Artificial neural networks',
    'Asbestos removal regulations',
    'Asphalt mixes',
    'Assessment of risks and threats',
    'Assessment processes',
    'Asset management',
    'Assistive instruments',
    'Astronomy',
    'Atlassian Bamboo',
    'Atlassian Bitbucket',
    'Atlassian Confluence',
    'Atlassian JIRA',
    'Auction characteristics',
    'Audio editing software',
    'Audio technology',
    'Audit techniques',
    'Augmented reality',
    'Authoring software',
    'AutoCAD',
    'Autodesk AutoCAD',
    'Autodesk AutoCAD Civil 3D',
    'Autodesk Inventor',
    'Autodesk Revit',
    'Automatic control system',
    'Automatic meter reading',
    'Automation technology',
    'Aviation English',
    'AWS',
    'Azerbaijani',
    'Azure',
    'Banking activities',
    'Barbering techniques',
    'Bash',
    'Basic chemicals',
    'Basque',
    'Battery chemistry',
    'Battery components',
    'Battery fluids',
    'Behavioural disorders',
    'Behavioural science',
    'Belarusian',
    'Bengali',
    'Bentley MicroStation',
    'Berber',
    'Bicycle mechanics',
    'Bicycle sharing systems',
    'Bihari',
    'Bioeconomy',
    'Biological haematology',
    'Biology',
    'Biomechanics',
    'Biomedical engineering',
    'Biomedical science',
    'Biomedical techniques',
    'Biometrics',
    'Biophysics',
    'Biosecurity',
    'Biostatistics',
    'Biotechnology',
    'Biotechnology in aquaculture',
    'Blender',
    'Blockchain application areas',
    'Blockchain applications',
    'Blockchain concept application',
    'Blockchain-based services regulation',
    'Blood transfusion',
    'Blow moulding',
    'Blueprints',
    'Body language',
    'Book reviews',
    'Bookkeeping regulations',
    'Bootstrap',
    'Border Gateway Protocol BGP',
    'Bosnian',
    'Brand marketing techniques',
    'Breathing techniques',
    'Budgeting',
    'Buffing motions',
    'Building automation',
    'Building codes',
    'Building construction principles',
    'Building materials industry',
    'Bulgarian',
    'Business analysis',
    'Business communication',
    'Business Development',
    'Business incubation',
    'Business intelligence',
    'Business law',
    'Business loans',
    'Business management principles',
    'Business processes',
    'Business strategy concepts',
    'Business valuation techniques',
    'By-products',
    'C#',
    'C++',
    'CAD software',
    'Cadastral taxation',
    'CADD software',
    'CAE software',
    'Call quality assurance management',
    'Call routing',
    'Call-centre technologies',
    'Cameras',
    'Cancellation policies of service providers',
    'Candle making techniques',
    'Canva',
    'Capacity building',
    'Carpentry',
    'Cascading style sheets CSS',
    'Catalan',
    'Centrifugal force',
    'Ceramics glazes',
    'Channel marketing',
    'Characteristics of diamonds',
    'Characteristics of faces',
    'Characteristics of plants',
    'Characteristics of precious metals',
    'Check methods',
    'Chef',
    'Chemical preservation',
    'Chemistry',
    'Chemistry of wood',
    'Child protection',
    'Childbirth',
    'Chinese',
    'CI/CD',
    'Circular economy',
    'Circus aesthetics',
    'Cisco Webex',
    'Civil engineering',
    'Civil law',
    'Civil process order',
    'Classical antiquity',
    'Classical languages',
    'Cleaning products',
    'Cleaning techniques',
    'Climate change impact',
    'Climatology',
    'Clinical biochemistry',
    'Clinical cytology',
    'Clinical imaging techniques',
    'Clinical immunology',
    'Clinical microbiology',
    'Coaching techniques',
    'Coating substances',
    'Coffee characteristics',
    'Cognitive psychology',
    'Coining',
    'Cold forging',
    'Combination of flavours',
    'Commercial photography',
    'Common children''s diseases',
    'Communicable diseases',
    'Communication',
    'Communication disorders',
    'Communication principles',
    'Communication related to hearing impairment',
    'Communication sciences',
    'Communication studies',
    'Community education',
    'Community-led local development',
    'Compass navigation',
    'Competition law',
    'Composite materials',
    'Composition of diets',
    'Computational fluid dynamics',
    'Computer engineering',
    'Computer graphics',
    'Computer programming',
    'Computer science',
    'Computer simulation',
    'Computer technology',
    'Computer Vision',
    'Concurrent estate',
    'Conflict management',
    'Conflict Resolution',
    'Constitutional law',
    'Construction industry',
    'Construction legal systems',
    'Construction methods',
    'Consultation',
    'Consulting',
    'Consumer goods industry',
    'Consumer law',
    'Consumer protection',
    'Contamination exposure regulations',
    'Content development processes',
    'Content marketing strategy',
    'Content Writing',
    'Continuous improvement philosophies',
    'Contract law',
    'Control engineering',
    'Control systems',
    'Conveyancing',
    'Copyright legislation',
    'Copywriting',
    'Corporate law',
    'Correctional procedures',
    'Corrosion types',
    'Cosmetic dental procedures',
    'Cosmetic manicure',
    'Cosmetic pedicure',
    'Cosmetic skin treatment',
    'Counselling methods',
    'Court interpreting',
    'Court procedures',
    'Credit card payments',
    'Credit control processes',
    'Crime victims'' needs',
    'Crime victims'' rights',
    'Criminal law',
    'Criminology',
    'Crimping',
    'Crisis intervention',
    'Critical Thinking',
    'Croatian',
    'Cross-matching techniques for blood transfusions',
    'Crowdfunding',
    'Cultured pearls',
    'Curriculum objectives',
    'Curriculum standards',
    'Customer relationship management',
    'Customer segmentation',
    'Cutting technologies',
    'Czech',
    'Danish',
    'Dart',
    'Dassault Systemes SolidWorks',
    'Data Analysis',
    'Data analytics',
    'Data engineering',
    'Data ethics',
    'Data mining methods',
    'Data science',
    'Data visualisation software',
    'Data Visualization',
    'Database',
    'Debt classification',
    'Debt collection techniques',
    'Debt systems',
    'Deburring processes',
    'Deep learning',
    'Demography',
    'Dental anatomy',
    'Dentistry science',
    'Dependency on drugs',
    'Design drawings',
    'Design principles',
    'Design thinking',
    'Desktop publishing',
    'Deterioration of fish products',
    'Development delays',
    'Developmental psychology',
    'Diagnostic radiology',
    'Dies',
    'Dietary regimes',
    'Digital compositing',
    'Digital image processing',
    'Digital Marketing',
    'Digital media',
    'Digital systems',
    'Digitization',
    'Dip tank parts',
    'Dip-coating process',
    'Diplomatic principles',
    'Dipping tank types',
    'Disability types',
    'Diving equipment',
    'Diving operation requirements',
    'Django',
    'Docker',
    'Document sharing procedures',
    'Dog behaviour',
    'Domestic heating systems',
    'Dressmaking',
    'Driving examinations',
    'Drupal',
    'Dust usage for forging',
    'Dutch',
    'Earth science',
    'eClinicalWorks EHR software',
    'Eclipse IDE',
    'Eclipse Jersey',
    'Ecological principles',
    'Ecology',
    'Economics',
    'Ecosystems',
    'Editorial standards',
    'Education administration',
    'Education law',
    'Elasticsearch',
    'Election law',
    'Electric clocks',
    'Electric current',
    'Electric generators',
    'Electrical discharge',
    'Electrical engineering',
    'Electrical equipment regulations',
    'Electrical machines',
    'Electrical power safety regulations',
    'Electrical testing methods',
    'Electrical wiring diagrams',
    'Electrical wiring plans',
    'Electricity',
    'Electricity consumption',
    'Electricity market',
    'Electricity principles',
    'Electrolytic passivation process',
    'Electromagnetic spectrum',
    'Electromechanics',
    'Electronic communication',
    'Electronic equipment standards',
    'Electronic test procedures',
    'Electronics',
    'Electroplating',
    'Electroplating metal materials',
    'Electroplating processes',
    'Email Marketing',
    'Emergency cases',
    'Emergent technologies',
    'Emission standards',
    'Empirical analysis',
    'Employment law',
    'Energy',
    'Energy conservation',
    'Energy market',
    'Energy performance of buildings',
    'Energy storage systems',
    'Energy therapy',
    'Engine components',
    'Engineering principles',
    'English',
    'Engraving technologies',
    'Entrepreneurship',
    'Environmental engineering',
    'Environmental legislation',
    'Environmental management standards',
    'Environmental policy',
    'Enzymatic processing',
    'Epic Systems',
    'Epidemiology',
    'Ergonomics',
    'ESRI ArcGIS software',
    'Estonian',
    'Ethics',
    'Etiopathy',
    'Evolution of economic forecasts',
    'Excel (Advanced)',
    'Export control principles',
    'Express.js',
    'Extensible markup language XML',
    'Eye protection regulations',
    'Fabric types',
    'Facebook',
    'Family law',
    'Fasciatherapy',
    'Female reproductive system pathology',
    'Fertilisation principles',
    'Fibre optics',
    'Fibreglass laminating',
    'Figma',
    'Film studies',
    'Financial Analysis',
    'Financial capability',
    'Financial engineering',
    'Financial forecasting',
    'Financial jurisdiction',
    'Financial management',
    'Financial markets',
    'Financial Modeling',
    'Financial products',
    'Financial statements',
    'Fine arts',
    'Finnish',
    'Fire prevention procedures',
    'Fire protection engineering',
    'Fire safety regulations',
    'Fire-fighting systems',
    'Firebase',
    'Firmware',
    'First aid',
    'Fish identification and classification',
    'Fish varieties',
    'Fish welfare regulations',
    'Fisheries management',
    'Fishing industry',
    'Flammable fluids',
    'Flask',
    'Flood remediation equipment',
    'Floriculture',
    'Fluid mechanics',
    'Flutter',
    'Food colorants',
    'Footwear industry',
    'Foreign affairs',
    'Foreign affairs policy development',
    'Foreign languages for international careers',
    'Forensic anthropology',
    'Forensic intelligence',
    'Forensic linguistics',
    'Forest conservation',
    'Forest ecology',
    'Forging processes',
    'Forming of public opinion',
    'Fossil fuels',
    'Fraud detection',
    'Freight transport methods',
    'French',
    'Fuel cell types',
    'Fuel distribution systems',
    'Fuel gas',
    'Functionalities of machinery',
    'Fundamental veterinary sciences',
    'Funding methods',
    'Furniture wood types',
    'Galician',
    'Game theory',
    'Gas chromatography',
    'Gemstones',
    'Gender studies',
    'General medicine',
    'Geochemistry',
    'Geodesy',
    'Geographic areas',
    'Geographical routes',
    'Geography',
    'Geological time scale',
    'Geology',
    'Geomatics',
    'Geometry',
    'Geophysics',
    'Georgian',
    'Geriatrics',
    'German',
    'GIS/ArcGIS',
    'Git',
    'GitHub',
    'GitLab',
    'Glass coatings',
    'Glass tempering',
    'Glassworking',
    'Go',
    'Good laboratory practice',
    'Google Analytics',
    'Google Android',
    'Google Angular',
    'Google Cloud',
    'Google Docs',
    'Google Sheets',
    'Google Workspace software',
    'Government policy',
    'Government policy implementation',
    'Government representation',
    'Government social security programmes',
    'Grammar',
    'Graphic design',
    'GraphQL',
    'Greek',
    'Green logistics',
    'Green space strategies',
    'Gujarati',
    'Hair colouring',
    'Hair products',
    'Hair removal techniques',
    'Hairdressing',
    'Handling of dangerous goods',
    'Hardware components',
    'Hardware industry',
    'Hardware testing methods',
    'Hazardous waste storage',
    'Hazardous waste treatment',
    'Hazardous waste types',
    'Health and safety hazards underground',
    'Health and safety regulations',
    'Health care legislation',
    'Health care occupation-specific ethics',
    'Health care system',
    'Health education',
    'Health informatics',
    'Health, safety and hygiene legislation',
    'Hearing aids',
    'Hearing disability',
    'Hebrew',
    'Henry Schein Dentrix',
    'Herbicides',
    'Hibernate ORM',
    'Hindi',
    'Histology',
    'Historic architecture',
    'Historical methods',
    'History',
    'History of literature',
    'History of musical instruments',
    'History of philosophy',
    'History of theology',
    'Homeopathy',
    'Hoshin kanri strategic planning',
    'Hot forging',
    'HubSpot software',
    'Human anatomy',
    'Human ear',
    'Human physiology',
    'Human resource management',
    'Human resources department processes',
    'Humanitarian aid actors',
    'Hungarian',
    'Hybrid control systems',
    'Hydraulic fluid',
    'Hydraulic press parts',
    'Hydraulics',
    'Hydroelectricity',
    'Hypertext markup language HTML',
    'IBM DB2',
    'IBM SPSS Statistics',
    'IBM Terraform',
    'IBM WebSphere MQ',
    'Icelandic',
    'ICT hardware specifications',
    'ICT networking hardware',
    'Illegal substances',
    'Image formation',
    'Image recognition',
    'Immigration law',
    'Immunology',
    'Industrial design',
    'Industrial engineering',
    'Industrial heating systems',
    'Industrial paint',
    'Industrial research and development',
    'Industrial software',
    'Infection control',
    'Infections in food',
    'Informatica software',
    'Innovation in nursing',
    'Inorganic chemistry',
    'Insolvency law',
    'Instrument performance elements',
    'Instrumentation engineering',
    'Instrumentation equipment',
    'Insurance law',
    'Insurance market',
    'Integrated circuits',
    'Integrated food-energy systems',
    'Intellectual property law',
    'Interactive media',
    'Internal auditing',
    'International business',
    'International development',
    'International financial reporting standards',
    'International law',
    'International regulations for cargo handling',
    'International trade',
    'Interpreting modes',
    'Interview techniques',
    'Intuit QuickBooks',
    'Inventory management rules',
    'Investigation research methods',
    'iOS Development',
    'Irish',
    'Italian',
    'Japanese',
    'Java',
    'Javanese',
    'JavaScript',
    'JavaScript Object Notation JSON',
    'Jenkins',
    'Jenkins CI',
    'Job market offers',
    'Joint ventures',
    'Journalism',
    'jQuery',
    'JUnit',
    'Jupyter Notebooks',
    'Kazakh',
    'Kiln types',
    'Kindergarten school procedures',
    'Kinetics',
    'Knowledge base',
    'Korean',
    'Kotlin',
    'Kronos Workforce Timekeeper',
    'Kubernetes',
    'Kurdish',
    'Laboratory methods in biomedical sciences',
    'Laboratory techniques',
    'Laboratory-based sciences',
    'Labour legislation',
    'Labour market',
    'LabVIEW',
    'Lacquer paint applications',
    'Landscape analysis',
    'Language teaching methods',
    'Laravel',
    'Laser engraving methods',
    'Laser marking processes',
    'Laser types',
    'Lasers',
    'Lathe machine parts',
    'Latin',
    'Latvian',
    'Launching of satellites into orbit',
    'Law enforcement',
    'Law of non-marital cohabitation',
    'Law of obligation',
    'Leadership',
    'Leadership principles',
    'Lean manufacturing',
    'Learning difficulties',
    'Learning management systems',
    'Learning needs analysis',
    'Leasing characteristics',
    'Leasing process',
    'Leather colour chemistry',
    'Legal case management',
    'Legal requirements of ICT products',
    'Legal research',
    'Legal terminology',
    'Legal use-of-force',
    'Legislation in agriculture',
    'Legislation procedure',
    'Licences regulation',
    'Life sciences',
    'Lift safety legislation',
    'Lift safety mechanisms',
    'Lighting techniques',
    'Limburgish',
    'Linguistics',
    'Linux',
    'Lip reading',
    'Liquidity management',
    'Literary criticism',
    'Literary techniques',
    'Literature',
    'Lithuanian',
    'Local geography',
    'Logic',
    'Logistics',
    'Luxembourgish',
    'Macedonian',
    'Machine Learning',
    'Machinery load capacity',
    'Maintenance operations',
    'Make-up techniques',
    'Malay',
    'Maltese',
    'Manage healthcare staff',
    'Management department processes',
    'Manual draughting techniques',
    'Manufacturing processes',
    'Marathi',
    'Marine engineering',
    'Marine technology',
    'Market analysis',
    'Market entry planning',
    'Market entry strategies',
    'Market participants',
    'Market Research',
    'Marketing analytics',
    'Marketing management',
    'Marketing mix',
    'Marketing principles',
    'Marketo Marketing Automation',
    'Massage theory',
    'Massage types',
    'Material mechanics',
    'Materials engineering',
    'Mathematical modelling',
    'Mathematics',
    'MATLAB',
    'Mechanical clocks',
    'Mechanical composition of trams',
    'Mechanical forging press parts',
    'Mechanical systems',
    'Mechanical tools',
    'Mechanics',
    'Mechanics of motor vehicles',
    'Mechanics of trains',
    'Mechatronics',
    'Media law',
    'Media planning',
    'Media studies',
    'Medical device regulations',
    'Medical device test procedures',
    'Medical devices',
    'Medical devices materials',
    'Medical genetics',
    'Medical imaging technology',
    'Medical informatics',
    'Medical laboratory technology',
    'Medical statistics',
    'Medical studies',
    'Medical terminology',
    'Medicines',
    'MEDITECH software',
    'Mentoring',
    'Mergers and acquisitions',
    'Metal bending techniques',
    'Metal coating technologies',
    'Metal drawing processes',
    'Metal eroding technology',
    'Metal forming technologies',
    'Metal joining technologies',
    'Metal smoothing technologies',
    'Metal thermal conductivity',
    'Metallurgy',
    'Metalworking tools',
    'Meteorology',
    'Metrology',
    'Microassembly',
    'Microelectronics',
    'Micromechanics',
    'Microprocessors',
    'Microscopic techniques',
    'Microsensors',
    'Microsoft .NET Framework',
    'Microsoft Access',
    'Microsoft Active Directory',
    'Microsoft Active Server Pages ASP',
    'Microsoft ASP.NET',
    'Microsoft Azure software',
    'Microsoft Dynamics',
    'Microsoft Excel',
    'Microsoft Office software',
    'Microsoft Outlook',
    'Microsoft Power BI',
    'Microsoft PowerPoint',
    'Microsoft PowerShell',
    'Microsoft Project',
    'Microsoft SharePoint',
    'Microsoft SQL Server',
    'Microsoft SQL Server Integration Services SSIS',
    'Microsoft SQL Server Reporting Services SSRS',
    'Microsoft Team Foundation Server',
    'Microsoft Teams',
    'Microsoft Visio',
    'Microsoft Visual Basic',
    'Microsoft Visual Basic for Applications VBA',
    'Microsoft Visual Studio',
    'Microsoft Windows',
    'Microsoft Windows Server',
    'Microsoft Word',
    'Migration',
    'Military code',
    'Military combat techniques',
    'Military drill',
    'Military logistics',
    'Military weaponry',
    'Mobility disability',
    'Model based system engineering',
    'Modern languages',
    'Modern portfolio theory',
    'Molecular biology',
    'MongoDB',
    'Monte Carlo simulation',
    'Montenegrin',
    'Morality',
    'Mortgage loans',
    'Motion graphics',
    'Motor vehicle parts drawings',
    'Movement techniques',
    'Multidisciplinary research',
    'Multimedia systems',
    'Multimodal transport logistics',
    'Musculoskeletal anatomy',
    'Music and video industry',
    'Musical genres',
    'Musical notation',
    'MySQL',
    'Nanoelectronics',
    'Nanotechnology',
    'National generally accepted accounting principles',
    'National regulations on handling cargo',
    'Natural Language Processing',
    'Neurology',
    'Neurophysiology',
    'New vehicles on the market',
    'Newborn care',
    'Next.js',
    'Node.js',
    'Non-destructive testing',
    'Norwegian',
    'NoSQL',
    'Nuclear energy',
    'Nuclear medicine',
    'Nuclear reprocessing',
    'Numerical sequences',
    'NumPy',
    'Nursing principles',
    'Nursing science',
    'Occitan',
    'Occupational physiology',
    'Occupational therapy theories',
    'Oceanography',
    'Office software',
    'Older adults'' needs',
    'Online ads campaign techniques',
    'Operational research',
    'Operational tactics for emergency responses',
    'Opinion poll',
    'Optical character recognition software',
    'Optical components',
    'Optical engineering',
    'Optical equipment standards',
    'Optical glass characteristics',
    'Optical instruments',
    'Optics',
    'Optoelectronic devices',
    'Optoelectronics',
    'Optomechanical engineering',
    'Oracle Cloud software',
    'Oracle Database',
    'Oracle Java',
    'Oracle Java 2 Platform Enterprise Edition J2EE',
    'Oracle JavaServer Pages JSP',
    'Oracle PeopleSoft',
    'Oracle PL/SQL',
    'Oracle SQL Developer',
    'Oral surgery',
    'Organic chemistry',
    'Organisational structure',
    'Orthopaedic treatment alternatives',
    'Orthopaedics',
    'Packaging engineering',
    'Packaging functions',
    'Packaging processes',
    'Paediatrics',
    'Paleontology',
    'Pandas',
    'Paper chemistry',
    'Paper production processes',
    'Participant observation',
    'Participatory decision-making',
    'Patents',
    'Pathogenic microorganisms',
    'Pathology',
    'Pedagogy',
    'Peer group methods',
    'Percolation',
    'Periodisation',
    'Perl',
    'Persian',
    'Personal development',
    'Personal protective equipment',
    'Personality development theories',
    'Personnel management',
    'Pest control in plants',
    'Pet diseases',
    'Pharmaceutical chemistry',
    'Pharmaceutical drug development',
    'Pharmaceutical industry',
    'Pharmaceutical legislation',
    'Pharmaceutical manufacturing quality systems',
    'Pharmaceutical technology',
    'Pharmacokinetics',
    'Pharmacology',
    'Pharmacovigilance legislation',
    'Pharmacy law',
    'Philanthropy',
    'Philosophical schools of thought',
    'Philosophy',
    'Phonetics',
    'Photogrammetry',
    'Photographic lenses',
    'Photographic processing techniques',
    'Photography',
    'Photonics',
    'PHP',
    'Physics',
    'Plastic resins',
    'Plastic welding',
    'Plumbing tools',
    'Pneumatics',
    'Polish',
    'Political campaigning',
    'Political ideologies',
    'Political parties',
    'Political science',
    'Politics',
    'Polling techniques',
    'Pollution prevention',
    'Polymer chemistry',
    'Portfolio management in textile manufacturing',
    'Portuguese',
    'Post-processing of photographs',
    'PostgreSQL',
    'Power BI',
    'Power electronics',
    'Power engineering',
    'Practical lexicography',
    'Precious metals',
    'Precision engineering',
    'Precision measuring instruments',
    'Precision mechanics',
    'Prepress processes',
    'Press law',
    'Preventive medicine',
    'Pricing strategies',
    'Primary care',
    'Primary school procedures',
    'Principles of combustion engines',
    'Principles of mechanical engineering',
    'Printed circuit boards',
    'Printed circuit boards testing methods',
    'Printed goods processes',
    'Printing media',
    'Printing techniques',
    'Probability theory',
    'Problem Solving',
    'Procore software',
    'Procurement legislation',
    'Product data management',
    'Product packaging requirements',
    'Product usage risks analysis',
    'Production processes',
    'Programmable logic controller',
    'Project configuration management',
    'Project Management',
    'Project management methodology',
    'Project management principles',
    'Pronunciation techniques',
    'Property law',
    'Protection from natural elements',
    'Prototyping',
    'Psychiatric disorders',
    'Psychiatry',
    'Psychological concepts',
    'Psychological counselling methods',
    'Psychological diagnostics',
    'Psychological theories',
    'Psychological treatment measures',
    'Psychology',
    'Psychotherapy principles',
    'Public auction procedures',
    'Public finance',
    'Public health',
    'Public housing legislation',
    'Public law',
    'Public offering',
    'Public relations',
    'Public Speaking',
    'Publishing industry',
    'Punjabi',
    'Puppet',
    'Pyrotechnic articles legislation',
    'Python',
    'PyTorch',
    'Quality and cycle time optimisation',
    'Quality assurance methodologies',
    'Quality assurance procedures',
    'Quality of fish products',
    'Quality standards',
    'Quantitative analysis',
    'Radars',
    'Radiation physics in healthcare',
    'Radiation protection',
    'Railway law',
    'React',
    'React Native',
    'Real estate market',
    'Recreation activities',
    'Red Hat Enterprise Linux',
    'Red Hat OpenShift',
    'Redis',
    'Reflexology',
    'Refractive power',
    'Refrigerants',
    'Rehabilitation',
    'Relationship marketing',
    'Relaxation techniques',
    'Religious studies',
    'Remote sensing techniques',
    'Renewable energy',
    'Repossession',
    'Reprography',
    'Reputation management',
    'Research design',
    'Resource-efficient technologies',
    'Restorative justice',
    'Resuscitation',
    'Reverse engineering',
    'Revit',
    'Rhetoric',
    'Risk assessment for window cleaning',
    'Risk identification',
    'Risk management',
    'Risk transfer',
    'Rivet types',
    'Riveting machine types',
    'Road traffic laws',
    'Robotic components',
    'Robotics',
    'Romani',
    'Romanian',
    'Room aesthetics',
    'Root cause analysis',
    'Rope lashing',
    'Ruby',
    'Ruby on Rails',
    'Russian',
    'Rust',
    'Safety engineering',
    'Sales',
    'Sales department processes',
    'Salesforce software',
    'Salon management',
    'Sanding techniques',
    'Sanskrit',
    'SAP Concur',
    'SAP ERP',
    'SAP software',
    'Sardinian',
    'SAS',
    'Scaffolding components',
    'Scala',
    'School psychology',
    'Scientific computing',
    'Scientific literature',
    'Scientific modelling',
    'Scientific research methodology',
    'Scikit-learn',
    'Screen reader',
    'Screw types',
    'Secondary school procedures',
    'Securities',
    'Security engineering',
    'Security of assets legislation',
    'Security panels',
    'Security threats',
    'Selenium',
    'Semantics',
    'Semiconductors',
    'Sensors',
    'SEO/SEM',
    'Serbian',
    'ServiceNow',
    'Sex education',
    'Sexology',
    'Shell script',
    'Shell/Bash',
    'Sign language',
    'Sketch',
    'SketchUp',
    'Skin types',
    'Slack',
    'Slovak',
    'Slovenian',
    'SMED',
    'Social justice',
    'Social media management',
    'Social Media Marketing',
    'Social media marketing techniques',
    'Social network analysis',
    'Social pedagogy',
    'Social sciences',
    'Social security law',
    'Social work theory',
    'Sociology',
    'Soil science',
    'Solar energy',
    'Solar products',
    'Soldering techniques',
    'SolidWorks',
    'Source colour chemicals',
    'Source criticism',
    'Spanish',
    'Special needs education',
    'Speech techniques',
    'Spelling',
    'Splunk Enterprise',
    'Sport and exercise medicine',
    'Sport games rules',
    'Sport history',
    'Sports competition information',
    'Sports nutrition',
    'Spring Boot',
    'Spring Framework',
    'SPSS',
    'SQL',
    'Stata',
    'State estimation',
    'Statistical analysis system software',
    'Statistical process control',
    'Statistics',
    'Stenography',
    'Sterilization techniques',
    'Stock market',
    'Strategic Planning',
    'Structured query language SQL',
    'Style sheet languages',
    'Subsidiary operations',
    'Supabase',
    'Supervision of persons',
    'Supply chain management',
    'Supply chain principles',
    'Surface engineering',
    'Surveillance methods',
    'Survey techniques',
    'Surveying',
    'Sustainable development goals',
    'Sustainable manufacturing',
    'Sustainable technologies',
    'Svelte',
    'Swedish',
    'Swift',
    'Swimming pool chemicals',
    'Synthetic resins',
    'System backup best practice',
    'Systems development life-cycle',
    'Tableau',
    'Tailwind CSS',
    'Tamil',
    'Task algorithmisation',
    'Tax legislation',
    'Teamwork',
    'Teamwork principles',
    'Technical drawings',
    'Technical terminology',
    'Telecommunication industry',
    'Telecommunications engineering',
    'Telemarketing',
    'Telugu',
    'Temperature scales',
    'TensorFlow',
    'Teradata Database',
    'Terminology',
    'Terraform',
    'Test procedures',
    'Textile industry',
    'Textile measurement',
    'Textile printing technology',
    'Textile technologies',
    'Textile trends',
    'The MathWorks MATLAB',
    'Theology',
    'Theoretical lexicography',
    'Theories of personality',
    'Therapeutic massage',
    'Thermodynamics',
    'Thermoplastic materials',
    'TikTok',
    'Time Management',
    'Torch temperature for metal processes',
    'Toxicology',
    'Toys and games categories',
    'Toys and games industry',
    'Toys and games safety recommendations',
    'Toys and games trends',
    'Track geometry',
    'Trade union regulations',
    'Trademarks',
    'Trading law',
    'Traffic engineering',
    'Traffic signs',
    'Training subject expertise',
    'Transact-SQL',
    'Transcription methods',
    'Transmission technology',
    'Transmission towers',
    'Transport topography',
    'Transportation engineering',
    'Travel bookings processes',
    'Trends in fashion',
    'Trendwatching',
    'Trimble SketchUp Pro',
    'Turkish',
    'Type of file',
    'TypeScript',
    'Typography',
    'UI/UX Design',
    'Ukrainian',
    'Understand spoken Luxembourgish',
    'UNIX',
    'UNIX Shell',
    'Upholstery tools',
    'Urban planning',
    'Urban planning law',
    'Urdu',
    'Value-added tax law',
    'Ventilation systems',
    'Victimology',
    'Video Editing',
    'Video-games functionalities',
    'Video-games trends',
    'Vietnamese',
    'Vinyl records',
    'Virology',
    'Virtual reality',
    'Visual disability',
    'Visual flight rules',
    'Vocal techniques',
    'Vue.js',
    'Walloon',
    'Waste management',
    'Waste transport legislation',
    'Water policies',
    'Water pressure',
    'Water reuse',
    'Web analytics',
    'Welding techniques',
    'Welsh',
    'Wet tumbling',
    'Wicker materials',
    'Wicker weaving techniques',
    'Wire harnesses',
    'Wireframing',
    'Wood cuts',
    'Wood moisture content',
    'Woodworking processes',
    'Woodworking tools',
    'WordPress',
    'Workday software',
    'Workplace sanitation',
    'World Wide Web Consortium standards',
    'Writing style guides',
    'Writing techniques',
    'Written Communication',
    'Yardi software',
    'Yeast fermentation principles',
    'Yiddish',
    'Zoning codes',
    'Zoo regulations',
    'Zoom'
  );

commit;
