-- =============================================================
-- Seed: 100 fake applicants on EVERY internship_listings row.
--
-- Strategy: reuse one pool of 100 fake students (IDs fd000000-…001
-- through …100) and apply each one to every listing. With ~200
-- listings that's ~20k applications. The applications row's unique
-- (student_id, listing_id) constraint means re-running is safe.
--
-- Prereqs:
--  1. seed_fake_jobs.sql has been run (creates the listings)
--  2. 2026-06-24-pipeline-stages.sql has been run (creates the Applied
--     anchor stage on every listing)
--
-- All fake student auth users use password: testpass1
-- All fake IDs use prefix fd... so cleanup is one DELETE.
-- =============================================================
create extension if not exists pgcrypto;

do $$
declare
  i int;
  uid uuid;
  full_name text;
  first_name text;
  last_name text;
  email text;
  major text;
  listing_row record;
  applied_stage_id uuid;
  total_listings int;
  total_apps_inserted int := 0;
  first_names text[] := ARRAY[
    'Alex','Jordan','Sam','Casey','Riley','Morgan','Avery','Quinn','Drew','Skylar',
    'Reese','Rowan','Hayden','Emerson','Finley','Cameron','Bailey','Harper','Sage','Parker',
    'Phoenix','Charlie','Logan','Dakota','Ellis','Hollis','Marlowe','Kendall','Blake','Tatum'
  ];
  last_names text[] := ARRAY[
    'Smith','Johnson','Brown','Garcia','Martinez','Lee','Patel','Kim','Nguyen','Anderson',
    'Walker','Hall','Allen','Young','King','Wright','Lopez','Hill','Scott','Green',
    'Adams','Baker','Gonzalez','Nelson','Carter','Mitchell','Perez','Roberts','Turner','Phillips'
  ];
  majors text[] := ARRAY[
    'Communications','Marketing','English','Journalism','Public Relations',
    'Media Studies','Business','Sociology','Political Science','Advertising',
    'Computer Science','Economics','Psychology','History','Design'
  ];
begin
  -- ----- Step 1: Ensure the 100-student pool exists -----
  for i in 1..100 loop
    uid := ('fd000000-0000-4000-d000-' || lpad(i::text, 12, '0'))::uuid;
    first_name := first_names[((i - 1) % array_length(first_names, 1)) + 1];
    last_name  := last_names[((i - 1) % array_length(last_names, 1)) + 1];
    full_name  := first_name || ' ' || last_name;
    email      := lower(first_name) || '.' || lower(last_name) || i::text || '@test.edu';
    major      := majors[((i - 1) % array_length(majors, 1)) + 1];

    insert into auth.users (
      id, instance_id, email, encrypted_password, email_confirmed_at,
      raw_user_meta_data, role, aud, created_at, updated_at,
      confirmation_token, recovery_token, email_change, email_change_token_new,
      email_change_token_current, phone_change, phone_change_token, reauthentication_token
    )
    values (
      uid, '00000000-0000-0000-0000-000000000000', email,
      crypt('testpass1', gen_salt('bf')), now(),
      jsonb_build_object('full_name', full_name, 'role', 'student'),
      'authenticated', 'authenticated', now(), now(),
      '', '', '', '', '', '', '', ''
    )
    on conflict (id) do nothing;

    insert into auth.identities (
      id, user_id, identity_data, provider, provider_id,
      last_sign_in_at, created_at, updated_at
    )
    values (
      uid, uid,
      jsonb_build_object('sub', uid::text, 'email', email),
      'email', uid::text, now(), now(), now()
    )
    on conflict (id) do nothing;

    insert into profiles (user_id, email, full_name, role, avatar_url, created_at, updated_at)
    values (uid, email, full_name, 'student', null, now(), now())
    on conflict (user_id) do nothing;

    insert into students (id, user_id, major, graduation_year, bio, created_at, updated_at)
    values (
      uid, uid, major, 2026 + (i % 3),
      'Test applicant ' || i || '. Generated by seed_100_applicants_per_listing.',
      now(), now()
    )
    on conflict (id) do nothing;
  end loop;

  -- ----- Step 2: For every listing, apply all 100 students -----
  select count(*) into total_listings from internship_listings;
  raise notice 'Seeding 100 applicants across % listings (% rows total)...',
    total_listings, total_listings * 100;

  for listing_row in select id from internship_listings loop
    select id into applied_stage_id
      from pipeline_stages
      where listing_id = listing_row.id and stage_type = 'applied'
      limit 1;

    if applied_stage_id is null then
      raise notice 'Skipping listing % — no Applied stage. Run the pipeline-stages migration first.', listing_row.id;
      continue;
    end if;

    for i in 1..100 loop
      uid := ('fd000000-0000-4000-d000-' || lpad(i::text, 12, '0'))::uuid;
      insert into applications (student_id, listing_id, stage_id, applied_at, updated_at)
      values (
        uid, listing_row.id, applied_stage_id,
        now() - ((100 - i) || ' minutes')::interval, now()
      )
      on conflict (student_id, listing_id) do nothing;

      if found then
        total_apps_inserted := total_apps_inserted + 1;
      end if;
    end loop;
  end loop;

  raise notice 'Done. % new applications inserted.', total_apps_inserted;
end $$;

-- =============================================================
-- CLEANUP — removes all 100 students + cascades their applications
-- =============================================================
-- delete from auth.users where id::text like 'fd000000-0000-4000-d000-%';
