export const INDUSTRIES = [
  'Technology',
  'Finance',
  'Healthcare',
  'Marketing',
  'Legal',
  'Engineering',
  'Education',
  'Media',
  'Nonprofit',
  'Government',
  'Retail',
  'Other',
] as const;

export type Industry = (typeof INDUSTRIES)[number];

export const MAJOR_TO_INDUSTRIES: Record<string, string[]> = {
  'Accounting': ['Finance', 'Government'],
  'Actuarial Science': ['Finance', 'Technology'],
  'Advertising': ['Marketing', 'Media'],
  'Aerospace Engineering': ['Engineering', 'Technology', 'Government'],
  'African American Studies': ['Education', 'Nonprofit', 'Government'],
  'Agricultural Science': ['Healthcare', 'Government'],
  'American Studies': ['Education', 'Government'],
  'Animal Science': ['Healthcare'],
  'Anthropology': ['Education', 'Nonprofit'],
  'Applied Mathematics': ['Technology', 'Finance', 'Engineering'],
  'Architecture': ['Engineering'],
  'Art History': ['Education', 'Media'],
  'Astronomy': ['Technology', 'Education'],
  'Biochemistry': ['Healthcare', 'Technology'],
  'Biomedical Engineering': ['Healthcare', 'Engineering', 'Technology'],
  'Biology': ['Healthcare', 'Education'],
  'Business Administration': ['Finance', 'Marketing', 'Retail'],
  'Chemical Engineering': ['Engineering', 'Healthcare'],
  'Chemistry': ['Healthcare', 'Engineering'],
  'Civil Engineering': ['Engineering', 'Government'],
  'Classics': ['Education'],
  'Cognitive Science': ['Technology', 'Healthcare'],
  'Communications': ['Media', 'Marketing'],
  'Computer Engineering': ['Technology', 'Engineering'],
  'Computer Science': ['Technology', 'Finance', 'Engineering'],
  'Construction Management': ['Engineering'],
  'Criminal Justice': ['Government', 'Legal'],
  'Cybersecurity': ['Technology', 'Government'],
  'Dance': ['Media', 'Education'],
  'Data Science': ['Technology', 'Finance', 'Healthcare'],
  'Dentistry (Pre-Dental)': ['Healthcare'],
  'Early Childhood Education': ['Education'],
  'Earth Science': ['Engineering', 'Government'],
  'Economics': ['Finance', 'Government'],
  'Education': ['Education', 'Nonprofit'],
  'Electrical Engineering': ['Engineering', 'Technology'],
  'Elementary Education': ['Education'],
  'English': ['Media', 'Education'],
  'Entrepreneurship': ['Technology', 'Finance', 'Marketing'],
  'Environmental Engineering': ['Engineering', 'Government'],
  'Environmental Science': ['Government', 'Nonprofit'],
  'Exercise Science': ['Healthcare'],
  'Fashion Design': ['Retail', 'Media'],
  'Film Studies': ['Media'],
  'Finance': ['Finance'],
  'Food Science': ['Healthcare', 'Retail'],
  'Foreign Languages': ['Education', 'Government'],
  'Forensic Science': ['Legal', 'Government'],
  'Forestry': ['Government', 'Nonprofit'],
  'Gender Studies': ['Nonprofit', 'Education'],
  'Genetics': ['Healthcare', 'Technology'],
  'Geography': ['Government', 'Education'],
  'Geology': ['Engineering', 'Government'],
  'Graphic Design': ['Media', 'Marketing', 'Technology'],
  'Health Administration': ['Healthcare', 'Government'],
  'Health Sciences': ['Healthcare'],
  'History': ['Education', 'Government'],
  'Hospitality Management': ['Retail'],
  'Human Resources': ['Finance', 'Retail'],
  'Industrial Engineering': ['Engineering', 'Technology'],
  'Information Systems': ['Technology', 'Finance'],
  'Information Technology': ['Technology'],
  'Interior Design': ['Retail', 'Media'],
  'International Business': ['Finance', 'Government'],
  'International Relations': ['Government', 'Nonprofit'],
  'Journalism': ['Media'],
  'Kinesiology': ['Healthcare'],
  'Law (Pre-Law)': ['Legal', 'Government'],
  'Liberal Arts': ['Education'],
  'Linguistics': ['Technology', 'Education'],
  'Management': ['Finance', 'Retail'],
  'Marine Biology': ['Healthcare', 'Government'],
  'Marketing': ['Marketing', 'Media', 'Retail'],
  'Materials Science': ['Engineering', 'Technology'],
  'Mathematics': ['Technology', 'Finance', 'Education'],
  'Mechanical Engineering': ['Engineering', 'Technology'],
  'Media Studies': ['Media', 'Marketing'],
  'Medicine (Pre-Med)': ['Healthcare'],
  'Meteorology': ['Government', 'Media'],
  'Microbiology': ['Healthcare'],
  'Military Science': ['Government'],
  'Music': ['Media', 'Education'],
  'Music Education': ['Education'],
  'Neuroscience': ['Healthcare', 'Technology'],
  'Nuclear Engineering': ['Engineering', 'Government'],
  'Nursing': ['Healthcare'],
  'Nutrition': ['Healthcare'],
  'Occupational Therapy': ['Healthcare'],
  'Oceanography': ['Government'],
  'Operations Management': ['Finance', 'Retail'],
  'Optometry (Pre-Optometry)': ['Healthcare'],
  'Pharmacy (Pre-Pharmacy)': ['Healthcare'],
  'Philosophy': ['Education', 'Legal'],
  'Photography': ['Media'],
  'Physical Therapy': ['Healthcare'],
  'Physics': ['Technology', 'Engineering'],
  'Political Science': ['Government', 'Legal', 'Nonprofit'],
  'Psychology': ['Healthcare', 'Education'],
  'Public Health': ['Healthcare', 'Government', 'Nonprofit'],
  'Public Policy': ['Government', 'Nonprofit'],
  'Public Relations': ['Marketing', 'Media'],
  'Real Estate': ['Finance'],
  'Religious Studies': ['Education', 'Nonprofit'],
  'Social Work': ['Nonprofit', 'Healthcare', 'Government'],
  'Sociology': ['Nonprofit', 'Education', 'Government'],
  'Software Engineering': ['Technology'],
  'Spanish': ['Education'],
  'Special Education': ['Education'],
  'Speech Pathology': ['Healthcare', 'Education'],
  'Sports Management': ['Marketing', 'Media'],
  'Statistics': ['Technology', 'Finance'],
  'Studio Art': ['Media'],
  'Supply Chain Management': ['Retail', 'Finance'],
  'Theater': ['Media', 'Education'],
  'Urban Planning': ['Government'],
  'Veterinary Science (Pre-Vet)': ['Healthcare'],
  'Web Development': ['Technology'],
  'Zoology': ['Healthcare', 'Education'],
  'Undecided': [],
  'Other': [],
};

export const MAJORS = [
  'Accounting',
  'Actuarial Science',
  'Advertising',
  'Aerospace Engineering',
  'African American Studies',
  'Agricultural Science',
  'American Studies',
  'Animal Science',
  'Anthropology',
  'Applied Mathematics',
  'Architecture',
  'Art History',
  'Astronomy',
  'Biochemistry',
  'Biomedical Engineering',
  'Biology',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Classics',
  'Cognitive Science',
  'Communications',
  'Computer Engineering',
  'Computer Science',
  'Construction Management',
  'Criminal Justice',
  'Cybersecurity',
  'Dance',
  'Data Science',
  'Dentistry (Pre-Dental)',
  'Early Childhood Education',
  'Earth Science',
  'Economics',
  'Education',
  'Electrical Engineering',
  'Elementary Education',
  'English',
  'Entrepreneurship',
  'Environmental Engineering',
  'Environmental Science',
  'Exercise Science',
  'Fashion Design',
  'Film Studies',
  'Finance',
  'Food Science',
  'Foreign Languages',
  'Forensic Science',
  'Forestry',
  'Gender Studies',
  'Genetics',
  'Geography',
  'Geology',
  'Graphic Design',
  'Health Administration',
  'Health Sciences',
  'History',
  'Hospitality Management',
  'Human Resources',
  'Industrial Engineering',
  'Information Systems',
  'Information Technology',
  'Interior Design',
  'International Business',
  'International Relations',
  'Journalism',
  'Kinesiology',
  'Law (Pre-Law)',
  'Liberal Arts',
  'Linguistics',
  'Management',
  'Marine Biology',
  'Marketing',
  'Materials Science',
  'Mathematics',
  'Mechanical Engineering',
  'Media Studies',
  'Medicine (Pre-Med)',
  'Meteorology',
  'Microbiology',
  'Military Science',
  'Music',
  'Music Education',
  'Neuroscience',
  'Nuclear Engineering',
  'Nursing',
  'Nutrition',
  'Occupational Therapy',
  'Oceanography',
  'Operations Management',
  'Optometry (Pre-Optometry)',
  'Pharmacy (Pre-Pharmacy)',
  'Philosophy',
  'Photography',
  'Physical Therapy',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Health',
  'Public Policy',
  'Public Relations',
  'Real Estate',
  'Religious Studies',
  'Social Work',
  'Sociology',
  'Software Engineering',
  'Spanish',
  'Special Education',
  'Speech Pathology',
  'Sports Management',
  'Statistics',
  'Studio Art',
  'Supply Chain Management',
  'Theater',
  'Urban Planning',
  'Veterinary Science (Pre-Vet)',
  'Web Development',
  'Zoology',
  'Undecided',
  'Other',
] as const;
